### ISSUE TITLE
idltool fetch need to work without a local repository.

### ISSUE THREAD

**Issue by morimekta** [morimekta/idltool#2]

**Comment by morimekta** [comment]
```bash
$ idl fetch github.com/zedge/recommender-libraries --verbose
Internal Error: null

java.lang.NullPointerException
    at net.morimekta.idltool.cmd.RemoteFetch.execute(RemoteFetch.java:98)
    at net.morimekta.idltool.IdlTool.execute(IdlTool.java:155)
    at net.morimekta.idltool.IdlTool.main(IdlTool.java:205)
```
